class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'cermin'
        self.UnzipMirrorCommand = 'unzipcermin'
        self.TarMirrorCommand = 'tarcermin'
        self.CancelMirror = 'gak'
        self.CancelAllCommand = 'gakall'
        self.ListCommand = 'list'
        self.StatusCommand = 'status'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AuthListCommand = 'authlist'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone'
        self.WatchCommand = 'yt'
        self.TarWatchCommand = 'taryt'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.RepoCommand = 'repo'

BotCommands = _BotCommands()
